import { ReactNode, useState, useRef } from 'react';
import { DashboardSidebar } from './DashboardSidebar';
import { DashboardHeader } from './DashboardHeader';
import { MobileDrawer } from './MobileDrawer';
import { BackToTop } from './BackToTop';
import { DocumentTitle } from './DocumentTitle';
import { LoadingOverlay } from './LoadingOverlay';
import { useDashboard } from '@/context/DashboardContext';
import { CurrencySymbol } from '@/lib/currency';

function PrintReportHeader() {
  const { client, dateRange } = useDashboard();
  const now = new Date();
  const exportDate = now.toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });
  const exportTime = now.toLocaleTimeString('en-US', { hour: '2-digit', minute: '2-digit' });

  return (
    <div className="print-report-header">
      <div>
        <h1>{client.name} — Performance Report</h1>
        <p style={{ fontSize: '9pt', color: 'hsl(215 16% 47%)', marginTop: '2mm' }}>
          Period: {dateRange} · Currency: <CurrencySymbol currency={client.currency} size={10} /> {client.currency}
        </p>
      </div>
      <div className="print-meta">
        <div>Exported: {exportDate} at {exportTime}</div>
        <div>Generated by Paid Media Dashboard</div>
      </div>
    </div>
  );
}

export function AppShell({ children }: { children: ReactNode }) {
  const [drawerOpen, setDrawerOpen] = useState(false);
  const { configLoaded, data } = useDashboard();

  // Keep the loading overlay visible until BOTH client settings AND the first
  // dashboard data fetch have resolved — so users see one continuous loading
  // state instead of a flash between phases. After the first successful load
  // we never re-show the blocking overlay (subsequent refetches are seamless).
  const firstLoadDoneRef = useRef(false);
  const initialLoading = !firstLoadDoneRef.current && (!configLoaded || data.loading);
  if (configLoaded && !data.loading) firstLoadDoneRef.current = true;

  return (
    <div className="flex min-h-screen w-full bg-background">
      <DocumentTitle />
      <div className="hidden lg:block">
        <DashboardSidebar />
      </div>
      <div className="lg:hidden">
        <MobileDrawer open={drawerOpen} onClose={() => setDrawerOpen(false)} />
      </div>
      <div className="flex flex-1 flex-col min-w-0">
        <DashboardHeader onMenuClick={() => setDrawerOpen(true)} />
        <main id="dashboard-main-content" className="flex-1 p-3 md:p-6 lg:p-8 overflow-auto">
          <PrintReportHeader />
          <div className="mx-auto max-w-[1400px] animate-fade-in">
            {children}
          </div>
        </main>
      </div>
      <div className="hidden lg:block">
        <BackToTop />
      </div>
      {initialLoading && <LoadingOverlay fixed message="Loading dashboard…" />}
    </div>
  );
}
